In [11]:
import pandas as pd

In [12]:
data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\pandas_practice_dataset.csv")
df=pd.DataFrame(data)

In [13]:
df.head(5)

,order_id,user_id,username,restaurant_name,order_date,amount,user_rating,rating,runs,matches,transaction_amount,product_price,is_premium,payment_status,review_text,playlist_name,creator_username
0,1001,7,user_0,Dosa House,2024-01-01,4161,20,NaN,120.0,NaN,17765,"₹2,499",True,Y,Excellent service,Workout Mix,dj_1
1,1002,20,user_1,Spice Villa,2024-01-04,3469,20,3.5,560.0,10.0,9600,"₹5,999",True,Y,Average,Workout Mix,dj_3
2,1003,15,user_2,Cafe Mocha,2024-01-07,362,4,3.5,560.0,20.0,4687,"₹2,499",False,No,Excellent service,Top Hits,dj_2
3,1004,11,user_3,Spice Villa,2024-01-10,723,3,3.5,250.0,10.0,4904,"₹1,299",False,No,Excellent service,Top Hits,dj_1
4,1005,8,user_4,Spice Villa,2024-01-13,1116,4,4.5,250.0,15.0,19611,₹999,True,yes,Great food,Top Hits,dj_2

In [14]:
spotify=pd.read_json(r"C:\Users\Divyansh yadav\Desktop\python_library\trending_songs.json")

df1=pd.DataFrame(spotify)

In [15]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   song     4 non-null      str
 1   artist   4 non-null      str
 2   streams  4 non-null      int64
 3   trend    4 non-null      str
dtypes: int64(1), str(3)
memory usage: 260.0 bytes

In [16]:
tsv=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\zomato_restaurants.tsv",sep='\t')

df2=pd.DataFrame(tsv)

In [17]:
df2.describe(include='all')

         restaurant       city  rating  cost_for_two
count             4          4   4.000      4.000000
unique            4          4     NaN           NaN
top     Spice Villa  Ahmedabad     NaN           NaN
freq              1          1     NaN           NaN
mean            NaN        NaN   4.325    700.000000
std             NaN        NaN   0.350    182.574186
min             NaN        NaN   3.900    500.000000
25%             NaN        NaN   4.125    575.000000
50%             NaN        NaN   4.350    700.000000
75%             NaN        NaN   4.550    825.000000
max             NaN        NaN   4.700    900.000000

In [18]:
flipkart=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\flipkart_com-ecommerce_sample.csv\flipkart_com-ecommerce_sample.csv",chunksize=2000)

for i,chunk in enumerate(flipkart,start=1):
  print(f"rows_2000 {i}")

rows_2000 1
rows_2000 2
rows_2000 3
rows_2000 4
rows_2000 5
rows_2000 6
rows_2000 7
rows_2000 8
rows_2000 9
rows_2000 10

In [19]:
paytm_data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\pandas_practice_dataset.csv")

print(paytm_data)

print("missing value in each column : ",paytm_data.isnull().sum())


null_columns=paytm_data.columns[paytm_data.isnull().any()]
# print(null_columns)

print("\n column containing null values")
for col in null_columns:
  print(col)

     order_id  user_id username restaurant_name  order_date  amount  \
0        1001        7   user_0      Dosa House  2024-01-01    4161
1        1002       20   user_1     Spice Villa  2024-01-04    3469
2        1003       15   user_2      Cafe Mocha  2024-01-07     362
3        1004       11   user_3     Spice Villa  2024-01-10     723
4        1005        8   user_4     Spice Villa  2024-01-13    1116
..        ...      ...      ...             ...         ...     ...
115      1116        8  user_10     Burger Town  2024-12-11    3050
116      1117       12  user_11       Pizza Hub  2024-12-14    4231
117      1118        2  user_12     Spice Villa  2024-12-17    4880
118      1119        1  user_13      Cafe Mocha  2024-12-20    4215
119      1120       16  user_14       Pizza Hub  2024-12-23    2468

     user_rating  rating   runs  matches  transaction_amount product_price  \
0             20     NaN  120.0      NaN               17765        ₹2,499
1             20     3.5  560.0     10.0                9600        ₹5,999
2              4     3.5  560.0     20.0                4687        ₹2,499
3              3     3.5  250.0     10.0                4904        ₹1,299
4              4     4.5  250.0     15.0               19611          ₹999
..           ...     ...    ...      ...                 ...           ...
115            3     3.5  560.0     20.0               15963        ₹5,999
116            4     NaN  430.0     20.0                2522          ₹999
117            4     3.5  560.0     20.0               19173          ₹999
118            2     4.5  250.0     20.0               15729        ₹1,299
119            3     NaN  430.0     15.0                1811        ₹5,999

    is_premium payment_status        review_text playlist_name  \
0         True              Y  Excellent service   Workout Mix
1         True              Y            Average   Workout Mix
2        False             No  Excellent service      Top Hits
3        False             No  Excellent service      Top Hits
4         True            yes         Great food      Top Hits
..         ...            ...                ...           ...
115      False            Yes  Excellent service      Top Hits
116          1             no  Excellent service   Workout Mix
117      False           Yes   Excellent service   Chill Vibes
118       True              Y            Average   Workout Mix
119        yes              N         Great food   Chill Vibes

    creator_username
0               dj_1
1               dj_3
2               dj_2
3               dj_1
4               dj_2
..               ...
115             dj_3
116             dj_3
117             dj_1
118             dj_3
119             dj_2

[120 rows x 17 columns]
missing value in each column :  order_id               0
user_id                0
username               0
restaurant_name        0
order_date             0
amount                 0
user_rating            0
rating                31
runs                  27
matches               16
transaction_amount     0
product_price          0
is_premium             0
payment_status         0
review_text            0
playlist_name          0
creator_username       0
dtype: int64

 column containing null values
rating
runs
matches