In [1]:
import pandas as pd

In [8]:
datee={
  "date":['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']}

df=pd.DataFrame(datee)

df['date']=pd.to_datetime(df['date'])

df

                 date
0 2024-06-01 14:30:00
1 2024-06-02 09:15:00
2 2024-06-03 20:45:00

In [14]:
flipkart_data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\flipkart_orders_raw.csv")

df=pd.DataFrame(flipkart_data)


df

   order_id customer           product    amount           order_date
0   FK10001   Vikram    Boat Earphones  20321.00  2024-10-16 03:01:47
1   FK10002    Nisha    Samsung 55" TV  53266.18  2023-04-15 21:47:57
2   FK10003     Neha          LEGO Set  54300.08  2023-02-02 00:05:13
3   FK10004   Manish          LEGO Set  37929.93  2024-07-28 06:45:41
4   FK10005    Rahul    PS5 Controller  72580.99  2024-04-04 18:17:51
5   FK10006      Raj    Boat Earphones  86161.01  2024-12-15 13:21:17
6   FK10007    Sneha         Kurti Set  76319.24  2023-12-11 03:05:24
7   FK10008   Anjali     OnePlus Watch  48398.66  2024-09-10 08:51:02
8   FK10009   Deepak  Whirlpool Fridge  79724.02  2024-01-23 02:35:18
9   FK10010     Amit     Redmi Note 13  59614.32  2024-01-06 18:12:45
10  FK10011    Sneha     Mixer Grinder  25233.23  2023-10-24 02:54:14
11  FK10012    Kavya    Boat Earphones  60413.71  2024-10-12 11:10:23
12  FK10013     Ritu      Canon Camera  15650.14  2024-12-19 21:41:04
13  FK10014   Vikram   Sony Headphones  57706.98  2023-09-08 05:29:24
14  FK10015    Vinod    PS5 Controller   5316.63  2024-07-24 07:43:20
15  FK10016     Amit    Boat Earphones  82207.31  2023-02-02 10:25:17
16  FK10017   Deepak     OnePlus Watch  35787.18  2024-08-03 22:20:13
17  FK10018      Raj    Boat Earphones  67124.51  2024-10-20 14:09:16
18  FK10019    Divya   Sony Headphones  52641.90  2024-07-05 08:47:37
19  FK10020    Meera    Samsung 55" TV  68092.66  2024-01-06 07:08:32
20  FK10021    Swati     Mixer Grinder  53796.89  2023-04-23 04:40:10
21  FK10022     Arun        Nike Shoes  87404.73  2024-01-30 12:38:29
22  FK10023    Swati   Sony Headphones  48465.24  2023-01-12 21:46:07
23  FK10024    Anita     Mixer Grinder  14485.75  2023-10-01 20:21:07
24  FK10025   Vikram          LEGO Set  68647.01  2023-01-04 23:56:46

In [15]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [16]:
df["Year"]= df["order_date"].dt.year
df["month"]= df["order_date"].dt.month
df["weekday"]= df["order_date"].dt.weekday
df["weekday_name"]= df["order_date"].dt.day_name()


df

,order_id,customer,product,amount,order_date,Year,month,weekday,weekday_name
0,FK10001,Vikram,Boat Earphones,20321.00,2024-10-16 03:01:47,2024,10,2,Wednesday
1,FK10002,Nisha,"Samsung 55"" TV",53266.18,2023-04-15 21:47:57,2023,4,5,Saturday
2,FK10003,Neha,LEGO Set,54300.08,2023-02-02 00:05:13,2023,2,3,Thursday
3,FK10004,Manish,LEGO Set,37929.93,2024-07-28 06:45:41,2024,7,6,Sunday
4,FK10005,Rahul,PS5 Controller,72580.99,2024-04-04 18:17:51,2024,4,3,Thursday
5,FK10006,Raj,Boat Earphones,86161.01,2024-12-15 13:21:17,2024,12,6,Sunday
6,FK10007,Sneha,Kurti Set,76319.24,2023-12-11 03:05:24,2023,12,0,Monday
7,FK10008,Anjali,OnePlus Watch,48398.66,2024-09-10 08:51:02,2024,9,1,Tuesday
8,FK10009,Deepak,Whirlpool Fridge,79724.02,2024-01-23 02:35:18,2024,1,1,Tuesday
9,FK10010,Amit,Redmi Note 13,59614.32,2024-01-06 18:12:45,2024,1,5,Saturday
10,FK10011,Sneha,Mixer Grinder,25233.23,2023-10-24 02:54:14,2023,10,1,Tuesday
11,FK10012,Kavya,Boat Earphones,60413.71,2024-10-12 11:10:23,2024,10,5,Saturday
12,FK10013,Ritu,Canon Camera,15650.14,2024-12-19 21:41:04,2024,12,3,Thursday
13,FK10014,Vikram,Sony Headphones,57706.98,2023-09-08 05:29:24,2023,9,4,Friday
14,FK10015,Vinod,PS5 Controller,5316.63,2024-07-24 07:43:20,2024,7,2,Wednesday
15,FK10016,Amit,Boat Earphones,82207.31,2023-02-02 10:25:17,2023,2,3,Thursday
16,FK10017,Deepak,OnePlus Watch,35787.18,2024-08-03 22:20:13,2024,8,5,Saturday
17,FK10018,Raj,Boat Earphones,67124.51,2024-10-20 14:09:16,2024,10,6,Sunday
18,FK10019,Divya,Sony Headphones,52641.90,2024-07-05 08:47:37,2024,7,4,Friday
19,FK10020,Meera,"Samsung 55"" TV",68092.66,2024-01-06 07:08:32,2024,1,5,Saturday
20,FK10021,Swati,Mixer Grinder,53796.89,2023-04-23 04:40:10,2023,4,6,Sunday
21,FK10022,Arun,Nike Shoes,87404.73,2024-01-30 12:38:29,2024,1,1,Tuesday
22,FK10023,Swati,Sony Headphones,48465.24,2023-01-12 21:46:07,2023,1,3,Thursday
23,FK10024,Anita,Mixer Grinder,14485.75,2023-10-01 20:21:07,2023,10,6,Sunday
24,FK10025,Vikram,LEGO Set,68647.01,2023-01-04 23:56:46,2023,1,2,Wednesday

In [9]:
df1 = pd.DataFrame({
    'post_id': [101, 102, 103, 104, 105, 106],
    'posted_at': [
        '2024-01-01 12:00:00',
        '2024-01-02 15:30:00',
        '2024-01-03 08:45:00',
        '2024-01-04 20:10:00',
        '2024-01-05 05:00:00',
        '2024-01-06 18:25:00'
    ]
})

# Convert to datetime and set timezone as UTC
df1['posted_at'] = pd.to_datetime(df1['posted_at'], utc=True)

# Convert UTC to Asia/Kolkata
df1['posted_at_kolkata'] = df1['posted_at'].dt.tz_convert('Asia/Kolkata')


print(df1['posted_at_kolkata'].head())

0   2024-01-01 17:30:00+05:30
1   2024-01-02 21:00:00+05:30
2   2024-01-03 14:15:00+05:30
3   2024-01-05 01:40:00+05:30
4   2024-01-05 10:30:00+05:30
Name: posted_at_kolkata, dtype: datetime64[us, Asia/Kolkata]

In [17]:
df["weekday_name"]=df["weekday_name"].apply(lambda x: True if x in ["Saturday","Sunday"] else False)
df["weekday_name"]

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9      True
10    False
11     True
12    False
13    False
14    False
15    False
16     True
17     True
18    False
19     True
20     True
21    False
22    False
23     True
24    False
Name: weekday_name, dtype: bool