In [1]:
import pandas as pd

In [2]:
zomato_order=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\restaurant_orders.csv")

df=pd.DataFrame(zomato_order)

df

,order_id,restaurant_name,order_date,order_time,items_ordered,order_value,delivery_time_mins
0,1001,Biryani Blues,29-01-2024,10:30,2,451.33,25.0
1,1002,Biryani Blues,29-01-2024,11:45,2,190.23,35.0
2,1003,Pizza Hut,09-05-2024,19:00,5,418.43,NaN
3,1004,Haldiram's,26-02-2024,17:30,1,1174.39,30.0
4,1005,Behrouz Biryani,18-04-2024,15:30,2,440.67,45.0
5,1006,McDonald's,24-01-2024,16:00,3,1294.12,40.0
6,1007,Box8,12-01-2024,21:45,5,318.52,50.0
7,1008,McDonald's,24-01-2024,14:30,5,409.59,25.0
8,1009,Burger King,18-06-2024,13:30,1,1304.68,25.0
9,1010,Haldiram's,12-03-2024,17:30,2,649.74,35.0
10,1011,Biryani Blues,09-03-2024,21:00,5,1007.22,NaN
11,1012,Behrouz Biryani,03-03-2024,12:45,4,514.43,NaN
12,1013,Pizza Hut,24-06-2024,15:00,2,1259.43,45.0
13,1014,Haldiram's,09-03-2024,11:15,5,1333.10,45.0
14,1015,Pizza Hut,16-06-2024,17:45,6,769.45,40.0
15,1016,Domino's,04-03-2024,21:30,6,939.19,50.0
16,1017,KFC,26-02-2024,12:45,1,1170.31,25.0
17,1018,Domino's,09-06-2024,12:45,5,235.76,50.0
18,1019,Faasos,29-04-2024,18:30,5,1312.05,20.0
19,1020,Biryani Blues,30-01-2024,20:30,6,609.24,40.0
20,1021,Haldiram's,10-02-2024,17:00,6,1332.40,40.0
21,1022,Wow Momo,15-02-2024,18:00,6,552.90,NaN
22,1023,Faasos,20-02-2024,12:30,2,878.16,NaN
23,1024,Swiggy Pop,01-01-2024,19:30,4,176.29,45.0
24,1025,Swiggy Pop,19-03-2024,13:00,2,1335.31,25.0
25,1026,McDonald's,04-05-2024,11:15,2,1040.66,NaN
26,1027,Domino's,08-03-2024,18:45,2,1404.03,35.0
27,1028,Behrouz Biryani,20-03-2024,16:30,4,1364.48,NaN
28,1029,McDonald's,04-03-2024,13:00,3,178.40,NaN
29,1030,Pizza Hut,30-05-2024,13:00,1,1105.59,20.0
30,1031,Pizza Hut,18-01-2024,10:30,1,844.11,40.0
31,1032,Biryani Blues,04-05-2024,13:15,6,1412.94,NaN
32,1033,Pizza Hut,01-05-2024,22:45,2,277.34,50.0
33,1034,KFC,18-04-2024,16:45,6,223.13,25.0
34,1035,Burger King,13-04-2024,21:30,1,485.69,35.0
35,1036,Wow Momo,24-04-2024,12:45,2,526.04,35.0
36,1037,Freshmenu,20-01-2024,17:00,1,1030.40,NaN
37,1038,Freshmenu,04-01-2024,11:15,2,698.66,NaN
38,1039,Pizza Hut,12-04-2024,10:15,4,152.91,50.0
39,1040,Subway,26-04-2024,14:45,6,1442.38,NaN
40,1041,Biryani Blues,04-05-2024,12:15,3,443.90,20.0
41,1042,Faasos,18-05-2024,10:30,1,217.69,NaN
42,1043,Wow Momo,15-05-2024,12:00,5,258.15,30.0
43,1044,McDonald's,01-06-2024,11:15,4,311.85,35.0
44,1045,Faasos,01-06-2024,10:00,4,1037.45,NaN
45,1046,KFC,07-03-2024,13:30,2,508.58,30.0
46,1047,Biryani Blues,14-06-2024,14:45,3,1404.17,25.0
47,1048,Burger King,27-04-2024,19:00,1,875.81,NaN
48,1049,Subway,03-02-2024,15:00,2,648.86,30.0
49,1050,Barbeque Nation,19-05-2024,21:30,5,1478.20,NaN

In [3]:
d=df[['restaurant_name','order_date']].duplicated()
print("duplicate order based on resturant_name and order_date :\n",d)

duplicate order based on resturant_name and order_date :
 0     False
1      True
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [4]:
flipkart_reviews=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\flipkart_reviews.csv")

df1=pd.DataFrame(flipkart_reviews)

In [5]:
a=df1['review_text'].value_counts()
print(a.head(3))

review_text
Excellent sound quality, highly recommend!    6
Picture quality is outstanding.               6
Good phone for the price.                     4
Name: count, dtype: int64

In [6]:
spotify_data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\spotify_playlists_raw.csv")

df2=pd.DataFrame(spotify_data)
df2=df2.drop_duplicates(spotify_data)

df2

,playlist_id,playlist_name,creator_username,total_songs,followers,genre
0,101,Bollywood Hits 2024,rahul_music,52,12400,Bollywood
1,102,Chill Vibes Only,priya_99,38,8750,Chill
2,103,Workout Beast Mode,fitlife_raj,45,15300,Workout
3,104,Late Night Lo-Fi,nightowl_sam,60,6200,Lo-Fi
4,105,Punjabi Dhol Beats,dhol_king,33,9800,Punjabi
6,106,Sunday Morning Jazz,jazzlover_anu,27,4300,Jazz
8,107,Top 50 Global,globalbeats,50,22100,Pop
10,108,Desi Pop Anthems,desipop_neha,41,7600,Desi Pop
12,109,Indie Folk Collection,indie_rohan,29,3100,Indie
15,110,EDM Drop Zone,edm_arjun,55,18900,EDM

In [7]:
insta_data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\instagram_users_raw.csv")

df3=pd.DataFrame(insta_data)

In [8]:
b=df3['username'].replace(['insta_queen','insta-queen'],'instaqueen')

print(b)

0       instaqueen
1      fitlife_raj
2       instaqueen
3     travel.diary
4       instaqueen
5      fitlife.raj
6       INSTAQUEEN
7     travel_diary
8       instaqueen
9      fitlife-raj
10     Insta_Queen
11     traveldiary
12     insta queen
13      fitliferaj
14      instaQueen
15    travel-diary
16     INSTA_QUEEN
17     fitlife_raj
18      instaqueen
19    travel.diary
Name: username, dtype: str

In [9]:
pytm_data=pd.read_csv(r"C:\Users\Divyansh yadav\Desktop\python_library\paytm_payments_raw.csv")

df4=pd.DataFrame(pytm_data)

df4

   transaction_id    user  amount payment_status
0         TXN1001   rahul     500            Yes
1         TXN1002   priya    1200           yes
2         TXN1003    amit     300              Y
3         TXN1004   sneha     850             NO
4         TXN1005     raj    2000             no
5         TXN1006   pooja     450             N
6         TXN1007   arjun    1750            yes
7         TXN1008    neha     600            Yes
8         TXN1009  vikram     980             Y
9         TXN1010   anita    1100             No
10        TXN1011   rohan     320            YES
11        TXN1012   kavya     760             no
12        TXN1013  suresh     430              y
13        TXN1014   divya    1500              N
14        TXN1015   kiran     890           Yes
15        TXN1016   meera     670              n
16        TXN1017    arun    2200            NO
17        TXN1018   nisha     540            Yes
18        TXN1019  sanjay    1300             y
19        TXN1020    ritu     410             no

In [10]:
#trimming and removing whitespaces
df4['payment_status_clean']=df4['payment_status'].str.strip()

#making value in lowercase
df4['payment_status_clean']=df4['payment_status_clean'].str.lower()

#replacing 1 by paid status and 0 byy unpaid status
df4['payment_status_clean']=df4['payment_status_clean'].replace(['yes','y','no','n'],[1,1,0,0])

df4

   transaction_id    user  amount payment_status payment_status_clean
0         TXN1001   rahul     500            Yes                    1
1         TXN1002   priya    1200           yes                     1
2         TXN1003    amit     300              Y                    1
3         TXN1004   sneha     850             NO                    0
4         TXN1005     raj    2000             no                    0
5         TXN1006   pooja     450             N                     0
6         TXN1007   arjun    1750            yes                    1
7         TXN1008    neha     600            Yes                    1
8         TXN1009  vikram     980             Y                     1
9         TXN1010   anita    1100             No                    0
10        TXN1011   rohan     320            YES                    1
11        TXN1012   kavya     760             no                    0
12        TXN1013  suresh     430              y                    1
13        TXN1014   divya    1500              N                    0
14        TXN1015   kiran     890           Yes                     1
15        TXN1016   meera     670              n                    0
16        TXN1017    arun    2200            NO                     0
17        TXN1018   nisha     540            Yes                    1
18        TXN1019  sanjay    1300             y                     1
19        TXN1020    ritu     410             no                    0